### ISSUE TITLE
Move Book.preview_url to Narration

### ISSUE THREAD

**Issue by nbeloglazov** [belaudiobooks/website#112]
Preview url points at youtube video that contains first chapter of a book. This is a Narration-level field, not Book. Additionally we need to render it it in the corresponding narration section for cases when there are multiple narrations. Example: https://audiobooks.by/books/orden-belai-myshy

**Comment by frombrest** [comment]
Since, book may has two or more narrations, it is not obvious to which narration preview link belongs. So, as I understand we should:

1. Create new column in `Narration` model
2. Write db migration to move url to narration level for books with single narration.
3. Rest of the books (with 2 or more narrations) must be handled manually.
4. Delete old preview field from `Book` model.

@nbeloglazov  Does this plan look right for you?

**Comment by nbeloglazov** [comment]
Yes, exactly that!

**Comment by nbeloglazov** [comment]
I think everything is done. Only to update data.json test.

**Comment by frombrest** [comment]
Seems like we are done. Can we close issue, or anything else?

**Comment by nbeloglazov** [comment]
Yes. Thank you again!
