### ISSUE TITLE
Move "duration" field to Narration model

### ISSUE THREAD

**Issue by nbeloglazov** [belaudiobooks/website#69]
At the moment book's duration is set on Book model. It should be set on Narration instead because different narration have different durations.

**Comment by frombrest** [comment]
Why we added `**/migrations/**` to the `.gitignore?` I guess we have to store db migrations with the code...

> The reason that there are separate commands to make and apply migrations is because you’ll commit migrations to your version control system and ship them with your app; they not only make your development easier, they’re also usable by other developers and in production.

Source: [https://docs.djangoproject.com/en/4.2/intro/tutorial02/#activating-models](https://docs.djangoproject.com/en/4.2/intro/tutorial02/#activating-models)

**Comment by nbeloglazov** [comment]
Yeah, fair question. I decided to try a bit unconventional approach here, at least at the beginning.

All data of the site is public and stored in https://github.com/belaudiobooks/data I manually sync production data to/from the github repo. During sync it completely destroys production DB, recreates tables from scratch and imports data. Given that data is relatively small and public (no user data) full re-import works ok. 

It helps to avoid migrations completely for now. And don't worry whether a change to models is compatible with migrations or not.

Though for this bug we'll need some custom logic that copies duration from Book field to the new field in Narration. Haven't thought about it. Maybe that's where using standard migration mechanism makes sense. I assume they allow to add custom sql or python code that updates data in DB after migrations.

**Comment by frombrest** [comment]
> Maybe that's where using standard migration mechanism makes sense.

If so, we have to completely switch to migration usage approach instead of backup&restore and do backup in parallel.
Also we need to commit initial (current) schema definition to the repo.

> I assume they allow to add custom sql or python code that updates data in DB after migrations.
Of course.. Just need to add new file with `class Migration(migrations.Migration):` And we can use either Python code to define migration logic or SQL script. 
Some examples:
https://docs.djangoproject.com/en/4.2/howto/writing-migrations/
https://www.endpointdev.com/blog/2016/09/executing-custom-sql-in-django-migration/

 One important thing to remember is: [Controlling the order of migrations](Controlling the order of migrations)
 > Django determines the order in which migrations should be applied not by the filename of each migration, but by building a graph using two properties on the Migration class: dependencies and run_before.

One more question: 
Book - Narration is one-to-many connection, so how can we determine right narration to copy duration from book model?

Should that be multistep process? Like: Add duration to narration, manually fill up narration records, Drop duration from book model

**Comment by nbeloglazov** [comment]
Committed initial migration script.

> Book - Narration is one-to-many connection, so how can we determine right narration to copy duration from book model?

> Should that be multistep process? Like: Add duration to narration, manually fill up narration records, Drop duration from book model

Yes, multistep makes sense. We can do a data migration as a second step that copies duration for books that has only one narration. But for books with multiple narrations we'll have to manually go through them and figure out which narration to update.

**Comment by nbeloglazov** [comment]
I merged PRs and updated `data` repo. Deployed the latest version to prod + checked that [data.json](https://audiobooks.by/data.json) looks correct I think it's done now! Thank you @frombrest !

**Comment by frombrest** [comment]
@nbeloglazov  Thanks for assistance and review!
